# Generated by Django 5.2.7 on 2025-11-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('round', models.IntegerField(default=1)),
                ('max_rounds', models.IntegerField(default=10)),
                ('alice_score', models.IntegerField(default=0)),
                ('bob_score', models.IntegerField(default=0)),
                ('oscar_score', models.IntegerField(default=0)),
                ('current_phase', models.CharField(choices=[('waiting', 'En attente'), ('drafting', 'Rédaction'), ('veto', 'Veto/Signature'), ('transmission', 'Transmission'), ('elimination', 'Élimination'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('current_turn', models.CharField(default='Alice', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('sender_role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('traitor_content', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('hash_val', models.CharField(blank=True, max_length=64, null=True)),
                ('is_compromised', models.BooleanField(default=False)),
                ('attack_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crypto_demo.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Alice', 'Alice'), ('Bob', 'Bob'), ('Oscar', 'Oscar')], max_length=10)),
                ('is_traitor', models.BooleanField(default=False)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='crypto_demo.game')),
            ],
        ),
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetos', to='crypto_demo.message')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_demo.player')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_demo.game')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='crypto_demo.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='crypto_demo.player')),
            ],
        ),
    ]
