# Generated by Django 5.2.7 on 2025-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='admin_password',
            field=models.CharField(default='admin123', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Alice', 'Alice'), ('Bob', 'Bob'), ('Oscar', 'Oscar'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
