# Generated by Django 5.2.7 on 2025-11-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_demo', '0002_game_admin_password_alter_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('certificate', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(default='document.txt', max_length=255)),
                ('encrypted_package', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='crypto_demo.cryptouser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='crypto_demo.cryptouser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
