# Generated by Django 5.2.7 on 2025-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_demo', '0003_cryptouser_encrypteddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddocument',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encrypteddocument',
            name='mime_type',
            field=models.CharField(default='text/plain', max_length=100),
        ),
    ]
